wordlist_films = [
{name: '12 angry men'},
{name: '12 years a slave'},
{name: '2001: a space odyssey'},
{name: '8 1/2'},
{name: 'a beautiful mind'},
{name: 'a christmas story'},
{name: 'a hard day&#39;s night'},
{name: 'a knight&#39;s tale'},
{name: 'alien'},
{name: 'amadeus'},
{name: 'amelie'},
{name: 'american beauty'},
{name: 'annie hall'},
{name: 'apocalypse now'},
{name: 'atonement'},
{name: 'avatar'},
{name: 'batman'},
{name: 'beauty and the beast'},
{name: 'before sunset'},
{name: 'ben-hur'},
{name: 'blade runner'},
{name: 'blue velvet'},
{name: 'braveheart'},
{name: 'brazil'},
{name: 'carrie'},
{name: 'casablanca'},
{name: 'casino'},
{name: 'chicago'},
{name: 'chinatown'},
{name: 'cinderella'},
{name: 'citizen kane'},
{name: 'city of god'},
{name: 'das boot'},
{name: 'die hard'},
{name: 'donnie darko'},
{name: 'downfall'},
{name: 'dr&#46; strangelove'},
{name: 'fargo'},
{name: 'ferris bueller&#39;s day off'},
{name: 'fight club'},
{name: 'finding nemo'},
{name: 'forrest gump'},
{name: 'frozen'},
{name: 'full metal jacket'},
{name: 'ghost'},
{name: 'gilda'},
{name: 'gladiator'},
{name: 'gone with the wind'},
{name: 'good will hunting'},
{name: 'goodfellas'},
{name: 'grave of the fireflies'},
{name: 'groundhog day'},
{name: 'guardians of the galaxy'},
{name: 'harry potter'},
{name: 'home alone'},
{name: 'howl&#39;s moving castle'},
{name: 'in the mood for love'},
{name: 'inception'},
{name: 'inside out'},
{name: 'interstellar'},
{name: 'iron man'},
{name: 'it&#39;s a wonderful life'},
{name: 'jaws'},
{name: 'jurassic park'},
{name: 'kill bill'},
{name: 'lawrence of arabia'},
{name: 'life is beautiful'},
{name: 'lord of the rings'},
{name: 'lost in translation'},
{name: 'mad max'},
{name: 'memento'},
{name: 'metropolis'},
{name: 'monty python and the holy grail'},
{name: 'mr&#46; smith goes to washington'},
{name: 'mulan'},
{name: 'mullholland drive'},
{name: 'my neighbor totoro'},
{name: 'no country for old men'},
{name: 'north by northwest'},
{name: 'oldboy'},
{name: 'out of africa'},
{name: 'pan&#39;s labyrinth'},
{name: 'platoon'},
{name: 'pocahontas'},
{name: 'princess mononoke'},
{name: 'psycho'},
{name: 'pulp fiction'},
{name: 'raging bull'},
{name: 'raiders of the lost ark'},
{name: 'rashomon'},
{name: 'rear window'},
{name: 'requiem for a dream'},
{name: 'rocky'},
{name: 'roman holiday'},
{name: 'romeo and juliet'},
{name: 'saving private ryan'},
{name: 'scarface'},
{name: 'schindler&#39;s list'},
{name: 'se7en'},
{name: 'seven samurai'},
{name: 'shrek'},
{name: 'shutter island'},
{name: 'sin city'},
{name: 'singin&#39; in the rain'},
{name: 'snow white'},
{name: 'some like it hot'},
{name: 'sophie&#39;s choice'},
{name: 'spirited away'},
{name: 'star wars'},
{name: 'sunset boulevard'},
{name: 'taxi driver'},
{name: 'the apartment'},
{name: 'the avengers'},
{name: 'the bridge on the river kwai'},
{name: 'the dark knight'},
{name: 'the departed'},
{name: 'the empire strikes back'},
{name: 'the english patient'},
{name: 'the godfather'},
{name: 'the grapes of wrath'},
{name: 'the incredibles'},
{name: 'the lion king'},
{name: 'the little mermaid'},
{name: 'the lives of others'},
{name: 'the martian'},
{name: 'the matrix'},
{name: 'the mummy'},
{name: 'the pianist'},
{name: 'the prestige'},
{name: 'the princess bride'},
{name: 'the shawshank redemption'},
{name: 'the shining'},
{name: 'the silence of the lambs'},
{name: 'the sixth sense'},
{name: 'the tree of life'},
{name: 'the truman show'},
{name: 'the usual suspects'},
{name: 'the wizard of oz'},
{name: 'there will be blood'},
{name: 'titanic'},
{name: 'to kill a mockingbird'},
{name: 'tokyo story'},
{name: 'toy story'},
{name: 'trainspotting'},
{name: 'unforgiven'},
{name: 'up'},
{name: 'vertigo'},
{name: 'wall-e'},
{name: 'yellow submarine'}
];
