wordlist_boardgames = [
{name: '7 wonders'},
{name: 'agricola'},
{name: 'avalon'},
{name: 'babel'},
{name: 'backgammon'},
{name: 'balderdash'},
{name: 'bananagrams'},
{name: 'bang'},
{name: 'battleship'},
{name: 'battlestar'},
{name: 'betrayal'},
{name: 'biblios'},
{name: 'blackjack'},
{name: 'blokus'},
{name: 'bridge'},
{name: 'candy land'},
{name: 'carcassone'},
{name: 'catan'},
{name: 'caverna'},
{name: 'charades'},
{name: 'checkers'},
{name: 'chess'},
{name: 'citadels'},
{name: 'clue'},
{name: 'codenames'},
{name: 'colt express'},
{name: 'cosmic encounter'},
{name: 'coup'},
{name: 'cranium'},
{name: 'cucumber'},
{name: 'diplomacy'},
{name: 'dixit'},
{name: 'dominion'},
{name: 'eclipse'},
{name: 'escape'},
{name: 'fish eat fish'},
{name: 'forbidden island'},
{name: 'ghost stories'},
{name: 'go'},
{name: 'go fish'},
{name: 'hanabi'},
{name: 'hearts'},
{name: 'jenga'},
{name: 'king of tokyo'},
{name: 'kingdom builder'},
{name: 'kingsburg'},
{name: 'life'},
{name: 'love letter'},
{name: 'mafia'},
{name: 'magic'},
{name: 'monopoly'},
{name: 'munchkin'},
{name: 'navegador'},
{name: 'no thanks'},
{name: 'nuns on the run'},
{name: 'operation'},
{name: 'pandemic'},
{name: 'pass the pigs'},
{name: 'pictionary'},
{name: 'poker'},
{name: 'power grid'},
{name: 'puerto rico'},
{name: 'red 7'},
{name: 'resistance'},
{name: 'reversi'},
{name: 'risk'},
{name: 'roborally'},
{name: 'saboteur'},
{name: 'scrabble'},
{name: 'set'},
{name: 'sherlock'},
{name: 'solitaire'},
{name: 'splendor'},
{name: 'spot it'},
{name: 'spyfall'},
{name: 'suburbia'},
{name: 'taboo'},
{name: 'takenoko'},
{name: 'telephone'},
{name: 'ticket to ride'},
{name: 'trivial pursuit'},
{name: 'tsuro'},
{name: 'uno'},
{name: 'vampire'},
{name: 'werewolf'}
];
