wordlist_starwars = [
{name: 'alien'},
{name: 'amputation'},
{name: 'antenna'},
{name: 'armor'},
{name: 'assassin'},
{name: 'asteroid'},
{name: 'attack'},
{name: 'bail'},
{name: 'blaster'},
{name: 'blueprint'},
{name: 'boba'},
{name: 'bounty hunter'},
{name: 'cantina'},
{name: 'cave'},
{name: 'choke'},
{name: 'chosen'},
{name: 'clone'},
{name: 'cloud city'},
{name: 'coruscant'},
{name: 'crash'},
{name: 'credit'},
{name: 'dark side'},
{name: 'death star'},
{name: 'deathstick'},
{name: 'decoy'},
{name: 'destiny'},
{name: 'disguise'},
{name: 'disney'},
{name: 'disturbance'},
{name: 'droid'},
{name: 'dungeon'},
{name: 'evaporator'},
{name: 'ewok'},
{name: 'explosion'},
{name: 'falcon'},
{name: 'fate'},
{name: 'finn'},
{name: 'first order'},
{name: 'fox'},
{name: 'galaxy'},
{name: 'general'},
{name: 'ghost'},
{name: 'hand'},
{name: 'hero'},
{name: 'hollywood'},
{name: 'hologram'},
{name: 'hope'},
{name: 'hutt'},
{name: 'hyperspace'},
{name: 'immortality'},
{name: 'jar jar'},
{name: 'jawa'},
{name: 'jedi'},
{name: 'laser'},
{name: 'lego'},
{name: 'light side'},
{name: 'lightning'},
{name: 'lightsaber'},
{name: 'lizard'},
{name: 'mace'},
{name: 'mask'},
{name: 'maul'},
{name: 'merchandise'},
{name: 'midichlorian'},
{name: 'mind trick'},
{name: 'moon'},
{name: 'myth'},
{name: 'phantom'},
{name: 'plans'},
{name: 'plasma'},
{name: 'princess'},
{name: 'prophecy'},
{name: 'prosthetic'},
{name: 'queen'},
{name: 'r2d2'},
{name: 'rancor'},
{name: 'rebellion'},
{name: 'republic'},
{name: 'rescue'},
{name: 'rey'},
{name: 'robe'},
{name: 'scavenger'},
{name: 'senate'},
{name: 'shield'},
{name: 'sith lord'},
{name: 'skywalker'},
{name: 'smuggler'},
{name: 'solo'},
{name: 'spaceport'},
{name: 'star destroyer'},
{name: 'stormtrooper'},
{name: 'suit'},
{name: 'swamp'},
{name: 'tattooine'},
{name: 'telekinesis'},
{name: 'telepathy'},
{name: 'temple'},
{name: 'the force'},
{name: 'tie fighter'},
{name: 'trader'},
{name: 'training'},
{name: 'trap'},
{name: 'twin'},
{name: 'vader'},
{name: 'vision'},
{name: 'wedge'},
{name: 'wookiee'},
{name: 'x-wing'},
{name: 'yoda'},
{name: 'youngling'}
];
